services:
  nextnotepad:
    image: omprakashornold/nextnotepad:v2.0.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID:-257847266541-iaqa70vcvoo61fbuk2aontn2edrpcagb.apps.googleusercontent.com}
    container_name: nextnotepad
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8080/" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
