// Auto-generated by scripts/bump-version.mjs during build/deployment. Do not edit directly.
export const APP_VERSION = {
  version: "0.1.1",
  buildNumber: 2,
  releaseDate: "September 15, 2026",
  shortDate: "Sep 15, 2026",
  isoDate: "2026-09-15",
  commitSha: "ab0024c",
} as const;
