// Auto-generated by scripts/bump-version.mjs during build/deployment. Do not edit directly.
export const APP_VERSION = {
  version: "0.1.7",
  buildNumber: 8,
  releaseDate: "October 2, 2026",
  shortDate: "Oct 2, 2026",
  isoDate: "2026-10-02",
  commitSha: "e75c273",
} as const;
