// Auto-generated by scripts/bump-version.mjs during build/deployment. Do not edit directly.
export const APP_VERSION = {
  version: "0.1.3",
  buildNumber: 4,
  releaseDate: "September 28, 2026",
  shortDate: "Sep 28, 2026",
  isoDate: "2026-09-28",
  commitSha: "9436bd8",
} as const;
