import type { ThemeModule } from "./types";

export const dracula: ThemeModule = {
  id: "dracula",
  label: "Dracula",
  monacoThemeId: "np-dracula",
  chrome: {
    background: "#2B2B2B",
    foreground: "#A9B7C6",
    panel: "#3C3F41",
    panelBorder: "#323232",
    menuHover: "#4B4E50",
    toolbarBackground: "#3C3F41",
    statusBarBackground: "#2B2B2B",
    statusBarForeground: "#A9B7C6",
    accent: "#4A88C7",
    accentForeground: "#FFFFFF",
    tabActiveBackground: "#4E5254",
    tabInactiveBackground: "#3C3F41",
    tabBorder: "#323232",
    scrollbar: "#555555",
    isDark: true,
  },
  monacoTheme: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "808080", fontStyle: "italic" },
      { token: "keyword", foreground: "CC7832" },
      { token: "string", foreground: "6A8759" },
      { token: "number", foreground: "6897BB" },
      { token: "type", foreground: "A9B7C6" },
      { token: "identifier", foreground: "A9B7C6" },
      { token: "function", foreground: "FFC66D" },
    ],
    colors: {
      "editor.background": "#2B2B2B",
      "editor.foreground": "#A9B7C6",
      "editor.lineHighlightBackground": "#323232",
      "editorLineNumber.foreground": "#606366",
      "editorLineNumber.activeForeground": "#A4A3A3",
      "editor.selectionBackground": "#214283",
      "editorCursor.foreground": "#BBBBBB",
      "editorWhitespace.foreground": "#3B3B3B",
      "editorIndentGuide.background": "#373737",
      "editorIndentGuide.activeBackground": "#5A5D60",
    },
  },
};
