import type { ThemeModule } from "./types";

export const notepadLight: ThemeModule = {
  id: "notepad-light",
  label: "Light",
  monacoThemeId: "np-notepad-light",
  chrome: {
    background: "#ffffff",
    foreground: "#18181b",
    panel: "#f8f8fa",
    panelBorder: "#e4e4e9",
    menuHover: "#eef0f5",
    toolbarBackground: "#f8f8fa",
    statusBarBackground: "#1e1e24",
    statusBarForeground: "#f4f4f5",
    accent: "#4f46e5",
    accentForeground: "#ffffff",
    tabActiveBackground: "#ffffff",
    tabInactiveBackground: "#f0f0f3",
    tabBorder: "#e4e4e9",
    scrollbar: "#cbd5e1",
    isDark: false,
  },
  monacoTheme: {
    base: "vs",
    inherit: true,
    rules: [
      { token: "comment", foreground: "008000" },
      { token: "keyword", foreground: "0000ff" },
      { token: "string", foreground: "a31515" },
      { token: "number", foreground: "098658" },
      { token: "type", foreground: "267f99" },
    ],
    colors: {
      "editor.background": "#ffffff",
      "editor.foreground": "#18181b",
      "editor.lineHighlightBackground": "#f8f9fa",
      "editorLineNumber.foreground": "#9ca3af",
      "editorLineNumber.activeForeground": "#4f46e5",
      "editor.selectionBackground": "#e0e7ff",
      "editorCursor.foreground": "#4f46e5",
      "editorWhitespace.foreground": "#e5e7eb",
      "editorIndentGuide.background": "#f3f4f6",
      "editorIndentGuide.activeBackground": "#cbd5e1",
    },
  },
};
