import type { ThemeModule } from "./types";

export const notepadLight: ThemeModule = {
  id: "notepad-light",
  label: "IntelliJ Light (New UI)",
  monacoThemeId: "np-intellij-light",
  chrome: {
    background: "#FFFFFF",
    foreground: "#1E1F22",
    panel: "#F7F8FA",
    panelBorder: "#DFE1E5",
    menuHover: "#EBECF0",
    toolbarBackground: "#F7F8FA",
    statusBarBackground: "#EBECF0",
    statusBarForeground: "#43454A",
    accent: "#3574F0",
    accentForeground: "#FFFFFF",
    tabActiveBackground: "#FFFFFF",
    tabInactiveBackground: "#F7F8FA",
    tabBorder: "#DFE1E5",
    scrollbar: "#C1C3C8",
    isDark: false,
  },
  monacoTheme: {
    base: "vs",
    inherit: true,
    rules: [
      { token: "comment", foreground: "8C8C8C", fontStyle: "italic" },
      { token: "keyword", foreground: "0033B3" },
      { token: "string", foreground: "067D17" },
      { token: "number", foreground: "1750EB" },
      { token: "type", foreground: "000000" },
      { token: "function", foreground: "00627A" },
    ],
    colors: {
      "editor.background": "#FFFFFF",
      "editor.foreground": "#1E1F22",
      "editor.lineHighlightBackground": "#F5F8FE",
      "editorLineNumber.foreground": "#818594",
      "editorLineNumber.activeForeground": "#1E1F22",
      "editor.selectionBackground": "#A6D2FF",
      "editorCursor.foreground": "#000000",
      "editorWhitespace.foreground": "#EBECF0",
      "editorIndentGuide.background": "#EBECF0",
      "editorIndentGuide.activeBackground": "#C1C3C8",
    },
  },
};
