import type { ThemeModule } from "./types";

export const notepadDark: ThemeModule = {
  id: "notepad-dark",
  label: "Dark",
  monacoThemeId: "np-notepad-dark",
  chrome: {
    background: "#141518",
    foreground: "#e2e8f0",
    panel: "#16171b",
    panelBorder: "rgba(255, 255, 255, 0.08)",
    menuHover: "#23252b",
    toolbarBackground: "#141518",
    statusBarBackground: "#101114",
    statusBarForeground: "#e2e8f0",
    accent: "#6366f1",
    accentForeground: "#ffffff",
    tabActiveBackground: "#1a1b20",
    tabInactiveBackground: "#121316",
    tabBorder: "rgba(255, 255, 255, 0.08)",
    scrollbar: "#334155",
    isDark: true,
  },
  monacoTheme: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "6a9955" },
      { token: "keyword", foreground: "569cd6" },
      { token: "string", foreground: "ce9178" },
      { token: "number", foreground: "b5cea8" },
      { token: "type", foreground: "4ec9b0" },
    ],
    colors: {
      "editor.background": "#141518",
      "editor.foreground": "#e2e8f0",
      "editor.lineHighlightBackground": "#1e2025",
      "editorLineNumber.foreground": "#4b5563",
      "editorLineNumber.activeForeground": "#a5b4fc",
      "editor.selectionBackground": "#3730a380",
      "editorCursor.foreground": "#818cf8",
      "editorWhitespace.foreground": "#27272a",
      "editorIndentGuide.background": "#1e2126",
      "editorIndentGuide.activeBackground": "#374151",
    },
  },
};
