import type { ThemeModule } from "./types";

export const notepadPlusPlus: ThemeModule = {
  id: "notepad-plus-plus",
  label: "Classic Light",
  monacoThemeId: "np-classic-light",
  chrome: {
    background: "#FFFFFF",
    foreground: "#000000",
    panel: "#F2F2F2",
    panelBorder: "#C4C4C4",
    menuHover: "#E5E5E5",
    toolbarBackground: "#F2F2F2",
    statusBarBackground: "#E0E0E0",
    statusBarForeground: "#000000",
    accent: "#2B78E4",
    accentForeground: "#FFFFFF",
    tabActiveBackground: "#FFFFFF",
    tabInactiveBackground: "#E8E8E8",
    tabBorder: "#C4C4C4",
    scrollbar: "#B8B8B8",
    isDark: false,
  },
  monacoTheme: {
    base: "vs",
    inherit: true,
    rules: [
      { token: "comment", foreground: "808080", fontStyle: "italic" },
      { token: "keyword", foreground: "000080" },
      { token: "string", foreground: "008000" },
      { token: "number", foreground: "0000FF" },
      { token: "function", foreground: "795E26" },
    ],
    colors: {
      "editor.background": "#FFFFFF",
      "editor.foreground": "#000000",
      "editor.lineHighlightBackground": "#FFE4C420",
      "editorLineNumber.foreground": "#787878",
      "editorLineNumber.activeForeground": "#000000",
      "editor.selectionBackground": "#A6D2FF",
      "editorCursor.foreground": "#000000",
      "editorWhitespace.foreground": "#E0E0E0",
      "editorIndentGuide.background": "#E8E8E8",
      "editorIndentGuide.activeBackground": "#A0A0A0",
    },
  },
};
