import type { ThemeModule } from "./types";

export const notepadLight: ThemeModule = {
  id: "notepad-light",
  label: "Light",
  monacoThemeId: "np-notepad-light",
  chrome: {
    background: "#fbfbfd",
    foreground: "#1d1d28",
    panel: "#f6f6fa",
    panelBorder: "#e3e3eb",
    menuHover: "#ececf7",
    toolbarBackground: "#f7f7fb",
    statusBarBackground: "#29265f",
    statusBarForeground: "#f8f7ff",
    accent: "#5754d9",
    accentForeground: "#ffffff",
    tabActiveBackground: "#ffffff",
    tabInactiveBackground: "#f3f3f8",
    tabBorder: "#e3e3eb",
    scrollbar: "#c5c7d2",
    isDark: false,
  },
  monacoTheme: {
    base: "vs",
    inherit: true,
    rules: [
      { token: "comment", foreground: "008000" },
      { token: "keyword", foreground: "0000ff" },
      { token: "string", foreground: "a31515" },
      { token: "number", foreground: "098658" },
      { token: "type", foreground: "267f99" },
    ],
    colors: {
      "editor.background": "#ffffff",
      "editor.foreground": "#1d1d28",
      "editor.lineHighlightBackground": "#f6f6fb",
      "editorLineNumber.foreground": "#a0a2af",
      "editorLineNumber.activeForeground": "#5754d9",
      "editor.selectionBackground": "#dddffd",
      "editor.inactiveSelectionBackground": "#ececfa",
      "editorCursor.foreground": "#5754d9",
      "editorWhitespace.foreground": "#e3e4eb",
      "editorIndentGuide.background1": "#eff0f4",
      "editorIndentGuide.activeBackground1": "#c8cad6",
      "editorGutter.background": "#fbfbfd",
      "editorOverviewRuler.border": "#00000000",
    },
  },
};
