import type { ThemeModule } from "./types";

export const notepadDark: ThemeModule = {
  id: "notepad-dark",
  label: "Dark (New UI)",
  monacoThemeId: "np-dark",
  chrome: {
    background: "#1E1F22",
    foreground: "#BCBEC4",
    panel: "#2B2D30",
    panelBorder: "#393B40",
    menuHover: "#393B40",
    toolbarBackground: "#1E1F22",
    statusBarBackground: "#2B2D30",
    statusBarForeground: "#868A91",
    accent: "#3574F0",
    accentForeground: "#FFFFFF",
    tabActiveBackground: "#2B2D30",
    tabInactiveBackground: "#1E1F22",
    tabBorder: "#393B40",
    scrollbar: "#43454A",
    isDark: true,
  },
  monacoTheme: {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "7A7E85", fontStyle: "italic" },
      { token: "keyword", foreground: "CF8E6D" },
      { token: "string", foreground: "6AAB73" },
      { token: "number", foreground: "2AACB8" },
      { token: "type", foreground: "BCBEC4" },
      { token: "identifier", foreground: "BCBEC4" },
      { token: "delimiter", foreground: "BCBEC4" },
      { token: "function", foreground: "56A8F5" },
    ],
    colors: {
      "editor.background": "#1E1F22",
      "editor.foreground": "#BCBEC4",
      "editor.lineHighlightBackground": "#26282E",
      "editorLineNumber.foreground": "#4B5059",
      "editorLineNumber.activeForeground": "#A1A3AB",
      "editor.selectionBackground": "#214283",
      "editorCursor.foreground": "#A1A3AB",
      "editorWhitespace.foreground": "#393B40",
      "editorIndentGuide.background": "#2B2D30",
      "editorIndentGuide.activeBackground": "#4E5157",
    },
  },
};
