import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, "..");

const pkgPath = path.join(rootDir, "package.json");
const versionTsPath = path.join(rootDir, "src", "lib", "constants", "version.ts");

// Read package.json
const pkgRaw = fs.readFileSync(pkgPath, "utf-8");
const pkg = JSON.parse(pkgRaw);

// Increment patch version (e.g. "0.1.0" -> "0.1.1")
const currentVersion = pkg.version || "0.1.0";
const parts = currentVersion.split(".").map((n) => parseInt(n, 10) || 0);
while (parts.length < 3) parts.push(0);
parts[2] += 1;
const newVersion = parts.join(".");

// Read existing build number if available
let buildNumber = 1;
if (fs.existsSync(versionTsPath)) {
  const content = fs.readFileSync(versionTsPath, "utf-8");
  const match = content.match(/buildNumber:\s*(\d+)/);
  if (match && match[1]) {
    buildNumber = parseInt(match[1], 10) + 1;
  }
}

// Format dates
const now = new Date();
const releaseDate = now.toLocaleDateString("en-US", {
  month: "long",
  day: "numeric",
  year: "numeric",
});
const shortDate = now.toLocaleDateString("en-US", {
  month: "short",
  day: "numeric",
  year: "numeric",
});
const isoDate = now.toISOString().split("T")[0];

// Git commit SHA if available
let commitSha = "";
try {
  commitSha =
    process.env.VERCEL_GIT_COMMIT_SHA?.slice(0, 7) ||
    process.env.GITHUB_SHA?.slice(0, 7) ||
    execSync("git rev-parse --short HEAD", { stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
} catch {
  commitSha = "";
}

// Update package.json
pkg.version = newVersion;
fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n", "utf-8");

// Write src/lib/constants/version.ts
const versionTsContent = `// Auto-generated by scripts/bump-version.mjs during build/deployment. Do not edit directly.
export const APP_VERSION = {
  version: "${newVersion}",
  buildNumber: ${buildNumber},
  releaseDate: "${releaseDate}",
  shortDate: "${shortDate}",
  isoDate: "${isoDate}",
  commitSha: "${commitSha}",
} as const;
`;

fs.writeFileSync(versionTsPath, versionTsContent, "utf-8");

console.log(
  `[Version] Auto-incremented to v${newVersion} (Build #${buildNumber}) - Released: ${releaseDate}${
    commitSha ? ` (${commitSha})` : ""
  }`
);
